#include <stdbool.h>
#include <stdio.h>
#include "object.h"
#include "toggle.h"
static const char *tags0[] = { "heaven", "little heaven", NULL};
static const char *tags1[] = { "portal", "respawn portal", NULL};
static const char *tags2[] = { "east", "west", "north", "south", NULL};
static const char *tags3[] = { "room", "waiting room", NULL};
static const char *tags4[] = { "wall", "east", "west", "north", "south", NULL};
static const char *tags5[] = { "nobody", NULL};
static const char *tags6[] = { "field", NULL};
static const char *tags7[] = { "cave", NULL};
static const char *tags8[] = { "forest", NULL};
static const char *tags9[] = { "silver", "coin", "silver coin", NULL};
static const char *tags10[] = { "gold", "coin", "gold coin", NULL};
static const char *tags11[] = { "guard", "burly guard", NULL};
static const char *tags12[] = { "basket", NULL};
static const char *tags13[] = { "jack", "warrior", "man", NULL};
static const char *tags14[] = { "jill", "valkyrie", "woman", NULL};
static bool condition15(void)  { return guard->health == 0 || silver->location == guard; }
static const char *tags15[] = { "east", "entrance", NULL};
static bool condition16(void)  { return !(*enterCave->condition)(); }
static const char *tags16[] = { "east", "entrance", NULL};
static const char *tags17[] = { "west", "exit", NULL};
static const char *tags18[] = { "forest entrance", NULL};
static const char *tags19[] = { "forest exit", NULL};
static const char *tags20[] = { "west", "north", "south", "grass", NULL};
static const char *tags21[] = { "east", "north", "rock", NULL};
static const char *tags22[] = { "backroom", NULL};
static const char *tags23[] = { "east", "west", "south", "rock", NULL};
static const char *tags24[] = { "south", "door", "doorway", NULL};
static const char *tags25[] = { "south", "door", "doorway", NULL};
static const char *tags26[] = { "north", "door", "doorway", NULL};
static const char *tags27[] = { "north", "door", "doorway", NULL};
static const char *tags28[] = { "box", "wooden box", NULL};
static const char *tags29[] = { "box", "wooden box", NULL};
static const char *tags30[] = { "box", "wooden box", NULL};
static const char *tags31[] = { "key", "tiny key", NULL};
static const char *tags32[] = { "lamp", NULL};
static const char *tags33[] = { "lamp", NULL};
static const char *tags34[] = { "club", "wooden club", NULL};
static const char *tags35[] = { "dagger", NULL};

static bool alwaysTrue(void) { return true; }

OBJECT objs[] = {
	{	/* 0 = heaven */
		alwaysTrue,
		 "little heaven",
		tags0,
		NULL,
		NULL,
		NULL,
		 "Everything looks so peaceful here.",
		"You see",
		"You can't get much closer than this.",
		 "It's where all the good adventurers go.",
		99,
		 9999,
		0,
		 100,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 1 = respawn */
		alwaysTrue,
		 "a respawn portal",
		tags1,
		 heaven,
		 field,
		 field,
		 "Looks like a gateway into the unknown.",
		"You see",
		 "A bright flash of light, and you are back in the field.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 2 = heavenEWNS */
		alwaysTrue,
		 "nothing but peace and quiet",
		tags2,
		 heaven,
		NULL,
		NULL,
		"You see nothing special.",
		"You see",
		 "In this dimension, there are no directions.",
		 "It's just a direction on the compass.",
		99,
		0,
		0,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 3 = waitingRoom */
		alwaysTrue,
		 "the waiting room",
		tags3,
		NULL,
		NULL,
		NULL,
		 "This is where all players start. Please enter: play YourName.",
		"You see",
		"You can't get much closer than this.",
		 "It's where all the bad adventurers have to stay.",
		99,
		 9999,
		0,
		 100,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 4 = waitingRoomWall */
		alwaysTrue,
		 "walls all around you",
		tags4,
		 waitingRoom,
		NULL,
		NULL,
		 "Written on the wall, it says: play Jack or play Jill.",
		"You see",
		 "You cannot go anywhere.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 5 = nobody */
		alwaysTrue,
		 "nobody",
		tags5,
		 waitingRoom,
		NULL,
		NULL,
		 "You are nobody. Please enter: play xxx",
		 "You have",
		"You can't get much closer than this.",
		"I know nothing about that.",
		99,
		 1,
		 100,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 6 = field */
		alwaysTrue,
		 "an open grassy field",
		tags6,
		NULL,
		NULL,
		NULL,
		 "The grassy field is a wide and calming space under a nightime sky.",
		"You see",
		"You can't get much closer than this.",
		 "It seems not often treaded.",
		99,
		 9999,
		0,
		 100,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 7 = cave */
		alwaysTrue,
		 "a little dark mountanside cave",
		tags7,
		NULL,
		NULL,
		NULL,
		 "The mountainside cave is a cold, dark, and rocky chamber.",
		"You see",
		"You can't get much closer than this.",
		 "It's dark in there; better bring a light source!.",
		99,
		 9999,
		0,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 8 = forest */
		alwaysTrue,
		 "dark miasma laden dark forest",
		tags8,
		NULL,
		NULL,
		NULL,
		 "The forest is an old, dark, and aged area with a tree cover obscuring the sky.",
		"You see",
		"You can't get much closer than this.",
		 "No one really knows what goes on in there.",
		99,
		 9999,
		0,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 9 = silver */
		alwaysTrue,
		 "a shining silver coin",
		tags9,
		 field,
		NULL,
		NULL,
		 "The coin has stalks of wheat tied with a ribbon engraved onto it.",
		"You see",
		"You can't get much closer than this.",
		 "Money makes the world go round...",
		 1,
		0,
		0,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 10 = gold */
		alwaysTrue,
		 "a blessed lustrous golden coin",
		tags10,
		 openBox,
		NULL,
		NULL,
		 "The coin is old and clearly has no known denomination and is a priceless aretefact.",
		"You see",
		"You can't get much closer than this.",
		 "Money makes the world go round...",
		 1,
		0,
		0,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 11 = guard */
		alwaysTrue,
		 "a burly guard",
		tags11,
		 field,
		NULL,
		NULL,
		 "The guard is a big and burly guy.",
		 "He has",
		"You can't get much closer than this.",
		 "He does his job stiffly but, every gear can be greased...",
		99,
		 20,
		 100,
		0,
		 -1,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 12 = basket */
		alwaysTrue,
		 "a worn out brown basket",
		tags12,
		 forest,
		NULL,
		NULL,
		 "The basket is an wood woven creation with a few holes in it.",
		"You see",
		"You can't get much closer than this.",
		 "Some say baskets are the last great human invention...",
		 3,
		 60,
		0,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 13 = jack */
		alwaysTrue,
		 "Jack",
		tags13,
		 field,
		NULL,
		NULL,
		 "Jack is a fearsome warrior.",
		 "Jack has",
		"You can't get much closer than this.",
		 "Jack is a fearsome warrior.",
		99,
		 20,
		 100,
		0,
		 -1,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 14 = jill */
		alwaysTrue,
		 "Jill",
		tags14,
		 field,
		NULL,
		NULL,
		 "Jill is a vicious valkyrie.",
		 "Jill has",
		"You can't get much closer than this.",
		 "Jill is a vicious valkyrie.",
		99,
		 20,
		 100,
		0,
		 -1,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 15 = enterCave */
		condition15,
		 "a cave entrance to the east",
		tags15,
		 field,
		 cave,
		 cave,
		 "The entrace is a wide opening in the mountain with a stone runic plaque above it.",
		"You see",
		 "You walk into the cave.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 16 = enterCaveBlocked */
		condition16,
		 "a cave entrance to the east",
		tags16,
		 field,
		NULL,
		 cave,
		 "The entrace is a wide opening in the mountain with a stone runic plaque above it.",
		"You see",
		 "The guard is stopping you from entering the cave.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 17 = exitCave */
		alwaysTrue,
		 "an exit to the west",
		tags17,
		 cave,
		 field,
		 field,
		 "The moon hangs in the sky in the opening through the cave wall.",
		"You see",
		 "You leave the cave.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 18 = enterForest */
		alwaysTrue,
		 "a forest entrance to the west",
		tags18,
		 field,
		NULL,
		 forest,
		 "The entrance is a gravel pathway with twisted trees forming the circular opening.",
		"You see",
		 "There is nothing stopping you from going forward.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 19 = exitForest */
		alwaysTrue,
		 "an exit to the east",
		tags19,
		 forest,
		 field,
		 field,
		 "The moon hangs above the sky that can be made out through the tree cover.",
		"You see",
		 "You walk out of the dark forest.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 20 = wallField */
		alwaysTrue,
		 "flat grass all around",
		tags20,
		 field,
		NULL,
		NULL,
		 "The field is surrounded by trees, roots, and undergrowth.",
		"You see",
		 "Dense forest growth is blocking the way.",
		 "You cannot go there, its pretty hard to get through.",
		99,
		0,
		0,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 21 = wallCave */
		alwaysTrue,
		 "solid rock all around",
		tags21,
		 cave,
		NULL,
		NULL,
		 "Carved into the stone is a secret password 'abcd'.",
		"You see",
		 "Solid rock is blocking the way.",
		 "You cannot go there, its just rock.",
		99,
		0,
		0,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 22 = backroom */
		alwaysTrue,
		 "a backroom",
		tags22,
		NULL,
		NULL,
		NULL,
		 "The room is dusty and messy.",
		"You see",
		"You can't get much closer than this.",
		 "There is definitely something in here worth hiding it away.",
		99,
		 9999,
		0,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 23 = wallBackroom */
		alwaysTrue,
		 "solid rock all around",
		tags23,
		 backroom,
		NULL,
		NULL,
		 "Rocky walls with embedded black stones.",
		"You see",
		 "Solid rock is blocking the way.",
		 "You cannot go there, its just bland wood.",
		99,
		0,
		0,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 24 = openDoorToBackroom */
		alwaysTrue,
		 "an open door to the south",
		tags24,
		NULL,
		 backroom,
		 backroom,
		 "The door is open.",
		"You see",
		 "You walk through the door into the backroom.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		0,
		0,
		 isAlreadyOpen,
		 toggleDoorToBackroom,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 25 = closedDoorToBackroom */
		alwaysTrue,
		 "a closed door to the south",
		tags25,
		 cave,
		NULL,
		 backroom,
		 "The door is closed.",
		"You see",
		 "The door is closed.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		0,
		0,
		 toggleDoorToBackroom,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 26 = openDoorToCave */
		alwaysTrue,
		 "an open door to the north",
		tags26,
		NULL,
		 cave,
		 cave,
		 "The door is open.",
		"You see",
		 "You walk through the door into the cave.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		0,
		0,
		 isAlreadyOpen,
		 toggleDoorToCave,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 27 = closedDoorToCave */
		alwaysTrue,
		 "a closed door to the north",
		tags27,
		 backroom,
		NULL,
		 cave,
		 "The door is closed.",
		"You see",
		 "The door is closed.",
		"I know nothing about that.",
		99,
		0,
		0,
		0,
		0,
		0,
		 toggleDoorToCave,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 28 = openBox */
		alwaysTrue,
		 "a wooden box",
		tags28,
		NULL,
		NULL,
		NULL,
		 "The box is open.",
		"You see",
		"You can't get much closer than this.",
		 "You need a key to open it.",
		 5,
		 20,
		0,
		0,
		0,
		0,
		 isAlreadyOpen,
		 toggleBox,
		 isStillOpen,
		 isAlreadyOpen
	},
	{	/* 29 = closedBox */
		alwaysTrue,
		 "a wooden box",
		tags29,
		NULL,
		NULL,
		NULL,
		 "The box is closed.",
		"You see",
		"You can't get much closer than this.",
		"I know nothing about that.",
		 5,
		0,
		0,
		0,
		0,
		0,
		 toggleBox,
		 isAlreadyClosed,
		 toggleBoxLock,
		 isAlreadyUnlocked
	},
	{	/* 30 = lockedBox */
		alwaysTrue,
		 "a wooden box",
		tags30,
		 backroom,
		NULL,
		NULL,
		 "The box is closed.",
		"You see",
		"You can't get much closer than this.",
		"I know nothing about that.",
		 5,
		0,
		0,
		0,
		0,
		0,
		 isStillLocked,
		 isAlreadyClosed,
		 isAlreadyLocked,
		 toggleBoxLock
	},
	{	/* 31 = keyForBox */
		alwaysTrue,
		 "a tiny key",
		tags31,
		 cave,
		NULL,
		NULL,
		 "The key is really small and shiny.",
		"You see",
		"You can't get much closer than this.",
		 "A small key opens a small lock.",
		 1,
		0,
		0,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 32 = lampOff */
		alwaysTrue,
		 "a lamp",
		tags32,
		 field,
		NULL,
		NULL,
		 "The lamp is off.",
		"You see",
		"You can't get much closer than this.",
		 "Essential tool for dark areas.",
		 5,
		0,
		0,
		0,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 33 = lampOn */
		alwaysTrue,
		 "a lamp",
		tags33,
		NULL,
		NULL,
		NULL,
		 "The lamp is on.",
		"You see",
		"You can't get much closer than this.",
		"I know nothing about that.",
		 5,
		0,
		0,
		 100,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 34 = club */
		alwaysTrue,
		 "a wooden club",
		tags34,
		 field,
		NULL,
		NULL,
		 "Two feet of solid wood.",
		"You see",
		"You can't get much closer than this.",
		"I know nothing about that.",
		 5,
		0,
		0,
		0,
		 -2,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 35 = dagger */
		alwaysTrue,
		 "a dagger",
		tags35,
		 field,
		NULL,
		NULL,
		 "The dagger is very sharp.",
		"You see",
		"You can't get much closer than this.",
		"I know nothing about that.",
		 7,
		0,
		0,
		0,
		 -5,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	}
}, *player = nobody;
